# Site settings
title: "[ zombie storage ]"
email: chris@zombie-storage.com
description: >
  Zombie storage is a place. A place like you and me. A place to put your decomposing, reanimated bodies. Safe, safe from harm and nasty hammers, shovels, crowbars, empty shotguns, bowling balls and other instruments of brain destruction. Bring out your risen dead and put them in this box.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zombie-storage.com"
twitter_username: tsagadai
github_username:  Tsagadai

# Build settings
markdown: kramdown
